//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumTests.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bład podczas wyłączania przegladarki: .
        /// </summary>
        internal static string Common_DisposeBrowserError {
            get {
                return ResourceManager.GetString("Common_DisposeBrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bład podczas inicjalizacji przegladarki: .
        /// </summary>
        internal static string Common_InitializeBrowserError {
            get {
                return ResourceManager.GetString("Common_InitializeBrowserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\.
        /// </summary>
        internal static string Common_PathToDriver {
            get {
                return ResourceManager.GetString("Common_PathToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string Common_TrueLowerCase {
            get {
                return ResourceManager.GetString("Common_TrueLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gry i Konsole.
        /// </summary>
        internal static string Ebay_Category {
            get {
                return ResourceManager.GetString("Ebay_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polska.
        /// </summary>
        internal static string Ebay_Country {
            get {
                return ResourceManager.GetString("Ebay_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sims 3.
        /// </summary>
        internal static string Ebay_ItemToSearch {
            get {
                return ResourceManager.GetString("Ebay_ItemToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string Ebay_MaximumPrice {
            get {
                return ResourceManager.GetString("Ebay_MaximumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Ebay_MinimumPrice {
            get {
                return ResourceManager.GetString("Ebay_MinimumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string Ebay_ProductDistanceRadius {
            get {
                return ResourceManager.GetString("Ebay_ProductDistanceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sims 3 in Gry i Konsole | eBay.
        /// </summary>
        internal static string Ebay_TitleToAssert {
            get {
                return ResourceManager.GetString("Ebay_TitleToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ebay.pl/sch/ebayadvsearch.
        /// </summary>
        internal static string Ebay_URL {
            get {
                return ResourceManager.GetString("Ebay_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bartmroz1999@gmail.com.
        /// </summary>
        internal static string JakDojade_TestLogin {
            get {
                return ResourceManager.GetString("JakDojade_TestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Q@W#E4r5t.
        /// </summary>
        internal static string JakDojade_TestPassword {
            get {
                return ResourceManager.GetString("JakDojade_TestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        internal static string JakDojade_TextToAssert {
            get {
                return ResourceManager.GetString("JakDojade_TextToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://jakdojade.pl/bydgoszcz/trasa.
        /// </summary>
        internal static string JakDojade_Url {
            get {
                return ResourceManager.GetString("JakDojade_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toruń Miasto.
        /// </summary>
        internal static string Train_EndStation {
            get {
                return ResourceManager.GetString("Train_EndStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bydgoszcz Wschód.
        /// </summary>
        internal static string Train_StartStation {
            get {
                return ResourceManager.GetString("Train_StartStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukano połączenia ze stacji BYDGOSZCZ WSCHÓD do stacji TORUŃ MIASTO.
        /// </summary>
        internal static string Train_TitleToAssert {
            get {
                return ResourceManager.GetString("Train_TitleToAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://portalpasazera.pl.
        /// </summary>
        internal static string Train_Url {
            get {
                return ResourceManager.GetString("Train_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azji.
        /// </summary>
        internal static string Wikipedia_EighthSearch {
            get {
                return ResourceManager.GetString("Wikipedia_EighthSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zjednoczone Emiraty Arabskie.
        /// </summary>
        internal static string Wikipedia_EndSearch {
            get {
                return ResourceManager.GetString("Wikipedia_EndSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zjednoczone Emiraty Arabskie – Wikipedia, wolna encyklopedia.
        /// </summary>
        internal static string Wikipedia_FinalTitle {
            get {
                return ResourceManager.GetString("Wikipedia_FinalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francja.
        /// </summary>
        internal static string Wikipedia_FirstSearch {
            get {
                return ResourceManager.GetString("Wikipedia_FirstSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aelii Flacylli.
        /// </summary>
        internal static string Wikipedia_FourthSearch {
            get {
                return ResourceManager.GetString("Wikipedia_FourthSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesarstwa Zachodniorzymskiego.
        /// </summary>
        internal static string Wikipedia_SecondSearch {
            get {
                return ResourceManager.GetString("Wikipedia_SecondSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenię.
        /// </summary>
        internal static string Wikipedia_SeventhSearch {
            get {
                return ResourceManager.GetString("Wikipedia_SeventhSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walensa.
        /// </summary>
        internal static string Wikipedia_SixthSearch {
            get {
                return ResourceManager.GetString("Wikipedia_SixthSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flawiusz Honoriusz.
        /// </summary>
        internal static string Wikipedia_ThirdSearch {
            get {
                return ResourceManager.GetString("Wikipedia_ThirdSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna.
        /// </summary>
        internal static string Wikipedia_Url {
            get {
                return ResourceManager.GetString("Wikipedia_Url", resourceCulture);
            }
        }
    }
}
